### ISSUE TITLE
Unable to run, java.lang.NoClassDefFoundError: org/apache/http/HttpRequest

### ISSUE THREAD

**Issue by Simon-Kaz** [opentable/wiremock-body-transformer#9]
I'm trying to run a standalone wiremock server with the body transformer using the following command

java -cp "wiremock-body-transformer-1.0.8.jar:wiremock-2.0.10-beta.jar" com.github.tomakehurst.wiremock.standalone.WireMockServerRunner --port 9876 --verbose --extensions com.opentable.extension.BodyTransformer

and I get the following error

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/HttpRequest
	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:98)
	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:62)
	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.main(WireMockServerRunner.java:110)
Caused by: java.lang.ClassNotFoundException: org.apache.http.HttpRequest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

- I tried both latest stable 1.5 and 2.0.10 beta
- I have httpcore-4.0.1.jar added to classpath

**Comment by KRoLer** [comment]
I'm not doing a deep investigation, but for me works fine the next configuration: 
- Create the folder **lib**
- Download HttpClient (https://hc.apache.org/downloads.cgi )
- Extract into the lib folder (You can leave files which start from http)
- Add to the classpath ./lib/*

For your case it will be: 
```
java -cp "wiremock-body-transformer-1.0.8.jar:wiremock-2.0.10-beta.jar:./lib/*" com.github.tomakehurst.wiremock.standalone.WireMockServerRunner --port 9876 --verbose --extensions com.opentable.extension.BodyTransformer
```

**Comment by Simon-Kaz** [comment]
Ah, I was doing it right but with the wrong jar file. I was using the HTTPCore jars rather than HTTPClient jars. It works now :) Thanks for pointing me in the right direction!

**Comment by tranhungt** [comment]
Thanks @KRoLer
